### ISSUE TITLE
Make trup detect and read message.txts and write them out

### ISSUE THREAD

**Issue by 6gk** [unixporn/trup-rs#12]
by elkowar: https://github.com/unixporn/trup/issues/168

Trup could autodetect message.txt files and as long as they're below a reasonable threshold (5000 characters? idk) write them out, split up into several messages.
Alternatively, this could be a command (`!long` or something, ran in the message that also sends the message.txt).

---

6gk:

> very bad idea. sounds extremely spammy and abuse-prone.
> a better solution could be to reupload to another service with a web interface (0x0.st, hastebin, pastebin, etc) & give a short preview, but even then it could be abused, at least it's not spammy though.

---

elkowar:

> i mean, uploading to a separate service sounds like a good compromise, yea,...
if you set a line-limit (specifically lines + a char limit still), it couldn't be alllll that spammy
> although I was informed that there are also betterdiscord plugins that show message.txt's, so maybe that's,..... a good enough workaround for me at least

**Comment by legendofmiracles** [comment]
I've added this. You can test it here: https://github.com/legendofmiracles/trup-rs

It doesn't show the first two lines (yet, to add or not?), because it uploads it to 0x0.st without downloading the message.txt and having to download would be quite a overhead.

**Comment by legendofmiracles** [comment]
Can be closed.

**Comment by elkowar** [comment]
Implemented in #18

**Comment by 6gk** [comment]
tfw when discord adds this feature natively 11 days after it gets implemented in a bot

:eyes: they're watching us
