### ISSUE TITLE
Rewrite progress

### ISSUE THREAD

**Issue by elkowar** [unixporn/trup-rs#15]
# Commands
- [x] ban
- [x] delban
- [x] desc
- [x] fetch
  - [x] normalize and validate fields where necessary
- [x] git
- [x] info
- [x] latency
- [x] modping
- [x] move
  - [x] only repeat pings
- [x] mute
  - [x] mutes should be logged in modlog
  - [x] response should probably be an embed
- [x] note
- [x] notes
  - [x]  mutes should show the duration
- [x] pfp
- [x] repo
- [x] restart
- [x] say
- [x] setfetch
- [x] warn
  - [x] show warn count in warn log embed
- [x] blocklist
- [x] top
- [x] poll
- [x] purge
- [x] role
- [x] help
  - [x] support `!help info` etc
- [x] unban

# Event-handlers
- [x] join events
- [x] leave events
- [x] message edits
- [x] message deletion

# Other functionality
- [x] poll single-vote enforcement
- [x] include context links everywhere it makes sense
- [x] keep-at-bottom CONTRIBUTING.md message in server-feedback
- [x] Media message logging

# Other TODO
- [x] Consistent embed format with timestamp etc
- [x] improve sql
  - [x] handle "upsert"s in profile via SQL
  - [x] de-shittify SQL query for notes
- [x] make embed formatting use things like **bold** etc
- [x] use embed for !setfetch explanation
- [x] show description at the top of fetch
- [x] fix setfetch
- [x] !git and !dotfiles should enforce URL format
- [ ] ~~!git and !dotfiles should print your own git and dotfiles when ran without arguments~~
- [x] fix memory unit in fetch to use KB rather than KiB
- [x] !help should only show non-mod commands for non-mods
- [x] if no mods are online/active, modping should ping the mods role
- [x] modping should only ping online mods
- [x] detect _who_ deleted a message and add that to the bot-messages entry
- [x] Numbers should _not_ always be treated as userids - users could be named `502`, for example.
- [x] error message for unknown user sucks
- [x] silent purge? (should this be _always_, or as an option?)
- [x] #feedback posts have the thumbs in the wrong order
- [x] bulk-deletions need to be logged in #bot-messages 
- [x] Helper-specific permissions
- [x] spam-detection
- [x] role-mentions should be handled by !role
- [x] success embed should be green
- [x] disambiguation and polls should be able to use the full 20 reactions that are possible
- [x] replace "banned" in ban-logs with "yote" because funny
- [x] replace "yeeted" with "yote"
- [x] ban should obviously not delban
- [x] update fetch image on showcase post
- [x] fix formatting of Memory in !top

- [x] insufficient permissions error message is shit (`requires helper_or_mod`)
- [x] notes does `now ago`
- [x] blocklist is missing usage
- [x] `Memorys` in top (use `s/ys$/ies/`)
- [x] `fetch <person> image` don't work :(
- [x] showcase submissions should be allowed to contain anything that embeds, no?
- [x] !roles command as an alias to !role
- [x] send :poggersphisch:, :police: and :starecry: emotes for the respective success, <mod-action> and error messages
- [x] notes are fucked (migration script issue)
- [ ] ~~ghostping thing should use :reee: and _not_ work in showcase~~ (do we want ghostping detection? currently just disabled it, idk)
- [x] top when doing like `!top Distro [aA]rch` without the backticks needs a good error message
- [x] !move should not ping the moving user
- [x] blocklist violations don't add notes currently
- [ ] ~~spam-protection for all accounts, not just young ones~~ (let's not, for now)
- [x] setfetch etc don't check blocklist before running (does this really need fix? :starecry:)
- [x] fetch migration - spaces etc in field names need to be adjusted, currently still fucked. i.e. DisplayProtocol vs "Display Protocol"
- [x] tag with spaces in name cannot be looked at :(
- [x] Failed unmute does not set mute as inactive, meaning that it'll continuously try to unmute them again and again
- [x] usage of blocklist should mention the backticks
- [x] error while handling `reaction_addd` event
- [x] !desc, !git and !dotfiles should gib error when not set  -> migration issue: empty strings in profiles table should be NULL
- [x] !poll multi literally just ded (no reactions)
- [x] be a bit less correct in the message.txt message
- [ ] ~~maybe use the bucket shit to avoid excessive rate limiting? idk prolly don't matter~~
- [x] command specific help should list subcommands properly
- [x] !poll  single vote enforcement broken?????
- [x] !poll without args should print usage (currently just deletes the msg)
- [x] help for mods is hitting the field limit - use pagination? two mesages?

**Comment by 6gk** [comment]
tfw tripled the todo list :crab: :crab: :crab: :crab:

**Comment by elkowar** [comment]
Rewrite is generally done! This can be closed, as everything that comes up now will be a normal feature/bugticket!
