### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by manderio** [unixporn/trup-rs#22]
Enable a highlight feature where you get a dm with context of conversation where your keyword was in the conversation, example for mander by highlight bot in different server:
![2021-03-20-130713_827x247_scrot](https://user-images.githubusercontent.com/59826300/111868936-37803b00-897d-11eb-9692-c92aaaa0de1d.png)

These are options that the bot has:
![2021-03-20-130758_466x527_scrot](https://user-images.githubusercontent.com/59826300/111868978-5088ec00-897d-11eb-86d0-b6e70decb196.png)

You set a list of highlights like so:
![2021-03-20-131105_334x372_scrot](https://user-images.githubusercontent.com/59826300/111869053-bffedb80-897d-11eb-8d0b-bf1f8cde0873.png)

Also deletes your list and message after a few seconds so people don't abuse your highligts to annoy you.

Highlights remain even if messages are deleted, so if you are mentioned and the conversation is deleted, the whole conversation is still preserved. 

Nothing necessary, just thought it would be a neat feature to add

Edit: realized that highlights don't activate while you are in chat, so for example, if someone is talking about mander and i sent a message in the same chat x seconds earlier, then i won't get a dm about it because I was there. Might be something to consider if you guys want to implement this

**Comment by elkowar** [comment]
Implemented in #29! Thanks for the feature-request
