### ISSUE TITLE
please change xubuntu logo

### ISSUE THREAD

**Issue by ekto** [unixporn/trup-rs#67]
![xubuntu logo](https://upload.wikimedia.org/wikipedia/commons/a/af/Xubuntu_logo.svg)

**Comment by JavaCafe01** [comment]
@ekto whats wrong with the current one?

**Comment by JavaCafe01** [comment]
@elkowar can we close this? I think that the logos should all stay as text-logo, and plus OP doesn't use xubuntu anymore.

**Comment by elkowar** [comment]
Sure!
