### ISSUE TITLE
[FEATURE] Add highlights through PMs

### ISSUE THREAD

**Issue by gwimm** [unixporn/trup-rs#85]
Title.

![image](https://user-images.githubusercontent.com/34531687/114840224-2eae4800-9e09-11eb-9e4f-96e2f034729c.png)

People will spam highlighted word after it was registered.

**Comment by legendofmiracles** [comment]
I did that, so that you can test if it works...

**Comment by manderio** [comment]
two proposed solutions: 
1. You can add highlights in dms
2. The command is deleted a few seconds after you have sent it in the server to hide what you added as well as your list

Both would be preferable but one of them should suffice.
