### ISSUE TITLE
[FEATURE REQUEST] You can post an image to showcase, then remove the attachment to have a plaintext message.

### ISSUE THREAD

**Issue by 6gk** [unixporn/trup-rs#98]
## Expected behaviour
Doesn't work

## Current behaviour
Works :/

## Additional info

you could probably do this with links too tbh - it'll show as edited anyway.  Or just upload a 1x1 image (only invisible on desktop though)....

**Comment by elkowar** [comment]
Has this ever actually been an issue? I haven't seen this before, and idk what people would gain from doing this...

**Comment by 6gk** [comment]
> Has this ever actually been an issue?

Once or twice (depending on your method of counting).

Ever.

---

Iirc someone posted a KDE setup (you can imagine the quality)

Someone else said "that's not yours here's an article that says how to make your kde look this bad"

Original guy said "yes that is mine" and probably attached something but I forgot what it was

(later in ricing-theming guy2 said that he knows guy1 and guy2 said that guy1 joined to troll)

---

🤷 this needs 200 priority!!!!!!!!!!!!!!!!!!!!!!!!!!!!! major issue!!!!!!!!!!!!!!
